const wordsByCategory = {
  general: [
    "apple",
    "astronaut",
    "backpack",
    "balloon",
    "banana",
    "bicycle",
    "camera",
    "castle",
    "dragon",
    "elephant",
    "fireworks",
    "guitar",
    "hamburger",
    "helicopter",
    "island",
    "jellyfish",
    "kangaroo",
    "lighthouse",
    "mountain",
    "octopus",
    "penguin",
    "pyramid",
    "rainbow",
    "robot",
    "sailboat",
    "snowman",
    "spaceship",
    "tornado",
    "umbrella",
    "volcano",
    "waterfall",
    "zebra",
  ],
  animals: [
    "alligator",
    "butterfly",
    "camel",
    "dolphin",
    "flamingo",
    "giraffe",
    "hedgehog",
    "koala",
    "lobster",
    "peacock",
    "raccoon",
    "shark",
    "tiger",
    "whale",
  ],
  food: [
    "burrito",
    "cupcake",
    "donut",
    "noodles",
    "pancake",
    "pizza",
    "popcorn",
    "sandwich",
    "spaghetti",
    "sushi",
  ],
};

function getRandomWords(count = 3, category = "general") {
  const pool = wordsByCategory[category] || wordsByCategory.general;
  return [...pool].sort(() => Math.random() - 0.5).slice(0, count);
}

module.exports = {
  wordsByCategory,
  getRandomWords,
};
